[pytest]
markers =
    core_test: Core test suite for release validation
filterwarnings =
    ignore:.*'soft_unicode' has been renamed to 'soft_str'*:DeprecationWarning
    ignore:unclosed file .*:ResourceWarning
env_files =
    test.env
testpaths =
    tests/unit
    tests/integration
    tests/functional
